---
title: ""
format: html
toc: false
---

# Research

## Working Papers

### [Irrigation in a Changing Landscape: A Combined Economic and Hydrologic Approach](https://essopenarchive.org/users/942971/articles/1313108-irrigation-adoption-in-a-changing-landscape-a-combined-economic-and-hydrologic-approach?commit=62e21d14537fc57479aa9d0180e41009a3b2df99)

*with Jamshid Jalali, Molly Sears, Sean A. Woznicki, Tao Liu, Oskar Marko, and Mirjana Radulović*

*Revise and Resubmit: Water Resources Research -- Agrohydrological Processes Under Global Change*

**Abstract:**\
Warmer temperatures and erratic rainfall patterns are threatening global water availability. Irrigation is a key risk-mitigation strategy, reducing farmers' dependence on rainfall and helping sustain crop yields. Limited research has examined farmers' likelihood of irrigating under climate change, or the effects of large-scale irrigation expansion on future water availability, largely due to challenges in acquiring field-level irrigation data. Using an integrated econometric-hydrologic modeling approach, we investigate how short- and long-run climatic conditions shape irrigation incentives and feasibility in Serbia---an increasingly water-stressed region---and how these incentives evolve under future climate scenarios. Our econometric model identifies when and where irrigation becomes a viable option under climate change. We then integrate these irrigation-enabled fields into the Soil and Water Assessment Tool Plus (SWAT+) to determine realized irrigation activity, irrigation water use, and the implications for future water availability. We find that farmers respond to both short- and long-term climate signals, with warmer and drier conditions strengthening irrigation incentives such that by 2060 irrigation becomes a viable option for an additional 11% of fields under the dry scenario and 3% under the wet scenario. This relatively modest expansion reflects binding infrastructure constraints, highlighting that even though climate change substantially strengthens incentives for irrigation, many fields remain unable to adapt. Nevertheless, our predicted irrigation expansion has meaningful consequences for water resources, exacerbating water balance deficits---particularly during dry years. Overall, our results demonstrate that climate-driven irrigation incentives and hydrological feedbacks must be jointly considered to ensure sustainable agricultural water management in the long run.

------------------------------------------------------------------------

## Ongoing Research

### Weathering the Change: Modeling Crop Choices in Response to Climate Variability

**Abstract:**\
Agricultural land allocation remains sensitive to climate change. As temperatures rise and precipitation patterns become more variable, farmers switch to crops better suited to the changing climate. While this substitution has tremendous market and welfare implications, quantifying these impacts remains understudied, largely due to limited data on adaptive decisions and challenges in measuring profitability. Using field-level data on cropping practices, we investigate how crop choices alter under
climate change. First, we estimate a yield-weather model to identify crop-specific thresholds for
extreme weather and predict the impact of climate change on yields. Results are then integrated into
a crop choice model to identify the key variables influencing farmers\' decisions and simulate how
choices differ under various climate scenarios. We estimate crop-specific yield-weather models
using for five crops: maize, soybean, sunflower, wheat, and rapeseed planted all across the region.
These models reveal crop-specific thresholds for extreme weather conditions and allow us to predict
yield changes under future climate scenarios. Integrating these yield model results into a panel
conditional logit crop choice model; we find that farmers adjust their crop choices in response
to evolving climatic and market conditions. Farmers switch away from profitable crops such as
maize and soybean to less profitable but more resilient wheat and sunflower. Our innovative crop
choice model incorporates climatic, hydrological, and economic factors, providing a more precise
representation of farmers\' decision-making processes. The findings highlight significant changes
in crop productivity and profitability under climate change, emphasizing the need for adaptive
strategies.

------------------------------------------------------------------------

### Can "Mafia" be Good? Evidence from Karachi's Urban Water Market

**Abstract:**\
In this paper, we investigate how households and non-state actors adapt to chronic water scarcity and infrastructural failures in developing countries. In many urban areas, unreliable and inadequate public water supply have given rise to the "water mafia" --- non-state actors that extract and sell water, often at high prices, to households disconnected from the piped network. The overall social welfare impact of these actors remains uncertain due to limited microdata on household-level adaptation to piped water scarcity. Leveraging a novel household survey that I designed and implemented in Karachi, Pakistan, I estimate a discrete--continuous model of household water demand and quantify the welfare changes from a counterfactual eliminating the water mafia. Preliminary findings reveal substantial disparities in piped water access, forcing poorer households to rely on illegal water vendors, creating opportunities for the mafia to engage in exploitative behavior.

------------------------------------------------------------------------

## Publications

#### [Assessing the Economic Cost of Depleting Groundwater in Balochistan: A Social Accounting Matrix (SAM) Multiplier Approach](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3822513)

*with Sania Haider Shikoh, Stephen Davies, Muhammad Saad Moeen, Abdul Wajid Rana, and Zeeshan Haider*

------------------------------------------------------------------------

#### [Estimating the Economic Impacts of the First Wave of COVID-19 in Pakistan Using a SAM Multiplier Model](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3787013)

*with Muhammad Saad Moeen, Zeeshan Haider, Sania Haider Shikoh, Amna Ejaz, Stephen Davies, and Abdul Wajid Rana*

------------------------------------------------------------------------

#### [Solarization of Electric Tube-wells for Agriculture in Balochistan: Economic and Environmental Viability](https://cgspace.cgiar.org/items/03ee14a4-03ac-4ff4-83e5-8c553c2ec6ff)

*with Abdul Wajid Rana, Stephen Davies, Muhammad Saad Moeen, and Sania Haider Shikoh*

------------------------------------------------------------------------

#### [What Explains Divergent Investment Performances in Asia-Pacific?](https://repository.unescap.org/items/b84c7d4b-040f-4c19-a8ac-1c6f19cffc3c)

*with Daniel Jeongdae Lee*

------------------------------------------------------------------------

## Media Spotlight

#### [Who pays for water? MSU researchers examine Karachi's water mafia, local experts reflect on Michigan's water woes](https://water.msu.edu/feature/who-pays-water-msu-researchers-examine-karachis-water-mafia-local-experts-reflect-michigans)

*MSU Water Alliance Feature, June 3, 2025*
